
networks:
  symfony-network:
    name: symfony-network
    driver: bridge

services:
  web:
    user: www-data
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-apache
    networks:
      - symfony-network
    restart: unless-stopped
    ports:
      - "${APACHE_PORT}:80"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: 0
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${APP_NAME}-maria
    networks:
      - symfony-network
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MARIADB_LOCAL_DIR}${MARIADB_DATA_DIR}:/var/lib/mysql
      - ${MARIADB_LOCAL_DIR}${MARIADB_CONF_DIR}:/etc/mysql/conf.d
      - ${MARIADB_LOCAL_DIR}${MARIADB_ETC_DIR}:/etc/mysql
