services:
  web:
    image: php:8.4-apache
    restart: always
    build: .
    container_name: ${APP_NAME}-apache
    volumes:
      - ./${APACHE_HTDOCS}:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache/symfony.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${APACHE_PORT}:80"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}"
    networks:
      - symfony-network

  db:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    container_name: ${APP_NAME}-mariadb
    volumes:
      - ${MARIADB_LOCAL_DIR}${MARIADB_DATA_DIR}:/var/lib/mysql
      - ${MARIADB_LOCAL_DIR}${MARIADB_CONF_DIR}:/etc/mysql/conf.d
      - ${MARIADB_LOCAL_DIR}${MARIADB_ETC_DIR}:/etc/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - symfony-network

  redis:
    image: redis:7
    restart: always
    container_name: ${APP_NAME}-redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  db_data:
